### PR TITLE
fix: make config structure valid if some fields are missing

### LINKED ISSUE #636: Generated config file is invalid when the AllowedIPs field is left blank
If the location doesn't have any allowedips set (which is optional), its generated config file (downloadable during the enrollment or from the dashboard) will be impossible to parse by the `wg-quick` command or the wireguard GUI client.

```
[#] ip link add lokacja type wireguard
[#] wg setconf lokacja /dev/fd/63
Line unrecognized: `AllowedIPs='
Configuration parsing error
[#] ip link delete dev lokacja
```

Currently the `AllowedIPs` line looks like this in such scenario:
```
AllowedIPs =
```

Instead, if there are no allowedips specified, it should be empty altogether. The issue doesn't occur when importing the config via the defguard client menu.

### PR DESCRIPTION
**Pull request by t-aleksander**
The issue is described in more detail in #636 

fixes #636

### CODE REVIEW

File: src/db/models/device.rs [hunk 1]
```diff
@@ -366,12 +366,21 @@ impl Device {
...
             None => String::new(),
         };
-        let allowed_ips = network
-            .allowed_ips
-            .iter()
-            .map(IpNetwork::to_string)
-            .collect::<Vec<String>>()
-            .join(",");
+
+        let allowed_ips: String = if network.allowed_ips.is_empty() {
```
Comment (j-chmielewski) [inline src/db/models/device.rs:370]: Unnecessary type

**Review by j-chmielewski — CHANGES_REQUESTED** [review]

**Review by j-chmielewski — APPROVED** [review]
